import {
  defineNuxtModule,
  createResolver,
  findPath,
  addPlugin,
  addTemplate,
  addImports,
  addComponent,
  addServerImportsDir,
  addRouteMiddleware,
  extendPages,
} from "@nuxt/kit";
import type { NuxtModule, NuxtPage } from "@nuxt/schema";
import type { NuxtI18nOptions, LocaleObject, ResolvedRoutingConfig } from "./types";
import { DEFAULT_DETECT_BROWSER_LANGUAGE } from "./runtime/defaults";

/** Public Nuxt-module option shape generated by `nuxt-module-build`. */
export type ModuleOptions = Partial<NuxtI18nOptions>;

// `nuxt-module-build` emits the published root declaration from this file,
// not from `src/index.ts`. Keep the public type vocabulary on the actual build
// entry so consumers resolving `@comvi/nuxt` receive the same surface.
export type {
  NuxtI18nOptions,
  LocaleObject,
  LocalePrefixMode,
  DetectBrowserLanguageOptions,
  ResolvedRoutingConfig,
  NuxtI18nRuntimeConfig,
  NuxtI18nPrivateRuntimeConfig,
  NuxtI18nSetupContext,
  NuxtI18nSetup,
  NuxtServerHost,
  NuxtServerLoaderHost,
  NuxtHostFactory,
  NuxtHostFactoryOptions,
  TranslationParams,
  TranslationResult,
  TranslationKeys,
  I18n,
} from "./types";

function normalizeLocales(locales: (string | LocaleObject)[]): {
  codes: string[];
  objects: Record<string, LocaleObject>;
} {
  const codes: string[] = [];
  const objects: Record<string, LocaleObject> = {};

  for (const locale of locales) {
    if (typeof locale === "string") {
      codes.push(locale);
      objects[locale] = { code: locale };
    } else {
      codes.push(locale.code);
      objects[locale.code] = locale;
    }
  }

  return { codes, objects };
}

/** Must not match params like `:localeId`. */
function isLocaleParamRoute(path: string): boolean {
  return /(?:^|\/):locale(?:$|[/?+*()])/u.test(path);
}

const comviNuxtModule: NuxtModule<NuxtI18nOptions> = defineNuxtModule<NuxtI18nOptions>({
  meta: {
    name: "@comvi/nuxt",
    configKey: "comvi",
    compatibility: {
      nuxt: "^3.0.0 || ^4.0.0",
    },
  },

  defaults: {
    locales: [],
    defaultLocale: "en",
    localePrefix: "as-needed",
    defaultNs: "default",
    icu: false,
    detectBrowserLanguage: DEFAULT_DETECT_BROWSER_LANGUAGE,
  },

  async setup(options, nuxt) {
    if (!options.locales || options.locales.length === 0) {
      console.warn(
        "[@comvi/nuxt] No locales configured. Add locales to your nuxt.config.ts comvi options.",
      );
    }

    const { resolve } = createResolver(import.meta.url);

    // A user module is addressed relative to srcDir first, then rootDir —
    // `findPath` throws on some malformed inputs, so each lookup is guarded.
    const findUserModule = async (specifier: string): Promise<string | undefined> => {
      for (const cwd of [nuxt.options.srcDir, nuxt.options.rootDir]) {
        try {
          const found = await findPath(specifier, { cwd, type: "file" });
          if (found) return found;
        } catch {
          // try the next root
        }
      }
      return undefined;
    };

    const resolvedSetupPath = await findUserModule(options.setup ?? "./comvi.setup");
    if (options.setup && !resolvedSetupPath) {
      throw new Error(`[@comvi/nuxt] Failed to resolve comvi.setup path: "${options.setup}".`);
    }

    const resolvedHostModulePath = options.hostModule
      ? await findUserModule(options.hostModule)
      : undefined;
    if (options.hostModule && !resolvedHostModulePath) {
      throw new Error(
        `[@comvi/nuxt] Failed to resolve comvi hostModule path: "${options.hostModule}".`,
      );
    }

    // A composed host picks its own compiler, so the module option would be
    // silently overruled rather than merged. Say so once, at build time.
    if (options.icu && resolvedHostModulePath) {
      console.warn(
        "[@comvi/nuxt] `comvi.icu` has no effect when `hostModule` is set — compose ICU in your host module.",
      );
    }

    const { codes: localeCodes, objects: localeObjects } = normalizeLocales(options.locales);

    const existingPublicRuntimeConfig = nuxt.options.runtimeConfig.public.comvi ?? {};
    const detectBrowserLanguageSource =
      existingPublicRuntimeConfig.detectBrowserLanguage ?? options.detectBrowserLanguage;

    const detectBrowserLanguage =
      detectBrowserLanguageSource === false
        ? false
        : {
            ...DEFAULT_DETECT_BROWSER_LANGUAGE,
            ...(typeof detectBrowserLanguageSource === "object" ? detectBrowserLanguageSource : {}),
          };

    const cookieName =
      typeof detectBrowserLanguage === "object"
        ? detectBrowserLanguage.cookieName
        : DEFAULT_DETECT_BROWSER_LANGUAGE.cookieName;

    const routingConfig: ResolvedRoutingConfig = {
      locales: localeCodes,
      localeObjects,
      defaultLocale: options.defaultLocale,
      localePrefix: options.localePrefix ?? "as-needed",
      cookieName,
    };

    nuxt.options.runtimeConfig.public.comvi = {
      ...existingPublicRuntimeConfig,
      locales: localeCodes,
      localeObjects,
      defaultLocale: options.defaultLocale,
      localePrefix: options.localePrefix ?? "as-needed",
      cookieName,
      cdnUrl: existingPublicRuntimeConfig.cdnUrl ?? options.cdnUrl,
      apiBaseUrl: existingPublicRuntimeConfig.apiBaseUrl ?? options.apiBaseUrl,
      defaultNs: existingPublicRuntimeConfig.defaultNs ?? options.defaultNs ?? "default",
      fallbackLocale:
        existingPublicRuntimeConfig.fallbackLocale ??
        options.fallbackLocale ??
        options.fallbackLanguage ??
        options.defaultLocale,
      defaultParams: existingPublicRuntimeConfig.defaultParams ?? options.defaultParams,
      basicHtmlTags: existingPublicRuntimeConfig.basicHtmlTags ?? options.basicHtmlTags,
      detectBrowserLanguage,
    };

    nuxt.options.runtimeConfig.comvi = {
      ...(nuxt.options.runtimeConfig.comvi ?? {}),
      ...(options.apiKey !== undefined ? { apiKey: options.apiKey } : {}),
    };

    nuxt.options.appConfig.comvi = {
      routing: routingConfig,
    };

    addPlugin({
      src: resolve("./runtime/plugin"),
      mode: "all",
    });

    addTemplate({
      filename: "comvi.setup.mjs",
      getContents: () => {
        const setupPath = resolvedSetupPath;

        if (!setupPath) {
          return `
export async function runComviSetup() {}
`;
        }

        return `
import userSetup from ${JSON.stringify(setupPath)};

export async function runComviSetup(context) {
  if (typeof userSetup !== "function") {
    throw new TypeError(
      "[@comvi/nuxt] comvi.setup must export a default function.",
    );
  }

  await userSetup(context);
}
`;
      },
    });

    // The host is decided HERE, at codegen: the same branch taken at runtime
    // would keep BOTH paths alive in every bundle. The default branch builds the
    // BASE host — ICU is the one capability with a module option, because it is
    // a constructor argument rather than something `.with()` can pipe on. Every
    // other capability arrives through `hostModule`, which is why that branch
    // forwards nuxt's RESOLVED options into the factory.
    addTemplate({
      filename: "comvi.host.mjs",
      getContents: () => {
        const hostPath = resolvedHostModulePath;

        if (!hostPath) {
          // Emitted only for `icu: true`: an app that did not ask for ICU must
          // get a module that cannot pull `@comvi/core/icu` into its graph.
          if (options.icu) {
            return `
import { createI18n } from "@comvi/vue";
import { createI18n as createCore } from "@comvi/core";
import { icuCompiler } from "@comvi/core/icu";

export function createComviI18n(options) {
  return createI18n({ ...options, compiler: icuCompiler });
}

export function createComviCore(options) {
  return createCore({ ...options, compiler: icuCompiler });
}
`;
          }

          return `
import { createI18n } from "@comvi/vue";
import { createI18n as createCore } from "@comvi/core";

export function createComviI18n(options) {
  return createI18n(options);
}

export function createComviCore(options) {
  return createCore(options);
}
`;
        }

        return `
import { createI18nFromCore } from "@comvi/vue";
import hostFactory from ${JSON.stringify(hostPath)};

function createHost(options) {
  if (typeof hostFactory !== "function") {
    throw new TypeError(
      "[@comvi/nuxt] comvi hostModule must export a default function returning an i18n host.",
    );
  }

  const host = hostFactory(options);

  if (!host || typeof host.t !== "function") {
    throw new TypeError(
      "[@comvi/nuxt] comvi hostModule's default export returned no i18n host. Return the composed host, e.g. createI18n(options).with(loader(map)).",
    );
  }

  return host;
}

export function createComviI18n(options) {
  const locale = options.ssrLocale ?? options.locale;

  return createI18nFromCore(createHost({ ...options, locale }), { ssrLocale: locale });
}

export function createComviCore(options) {
  return createHost(options);
}
`;
      },
    });

    // Explicit, so Nuxt generates stable #imports types for published package
    // consumers. Keep in sync with src/runtime/composables/ — asserted by
    // tests/module.test.ts.
    addImports([
      { name: "useI18n", from: resolve("./runtime/composables/useI18n") },
      { name: "useI18nLoader", from: resolve("./runtime/composables/capabilities") },
      { name: "useI18nPlugins", from: resolve("./runtime/composables/capabilities") },
      { name: "useLocaleHead", from: resolve("./runtime/composables/useLocaleHead") },
      { name: "useLocalePath", from: resolve("./runtime/composables/useLocalePath") },
      { name: "useLocaleRoute", from: resolve("./runtime/composables/useLocaleRoute") },
      { name: "useRouteConfig", from: resolve("./runtime/composables/useRouteConfig") },
      { name: "useSwitchLocalePath", from: resolve("./runtime/composables/useSwitchLocalePath") },
    ]);

    // Register runtime components explicitly to avoid async/global component chunk warnings.
    addComponent({
      name: "T",
      filePath: resolve("./runtime/components/T"),
      export: "default",
    });
    addComponent({
      name: "NuxtLinkLocale",
      filePath: resolve("./runtime/components/NuxtLinkLocale"),
      export: "default",
    });

    addServerImportsDir(resolve("./runtime/server/utils"));

    addRouteMiddleware({
      name: "i18n",
      path: resolve("./runtime/middleware/i18n.global"),
      global: true,
    });

    nuxt.options.build.transpile.push(resolve("./runtime"));

    nuxt.options.build.transpile.push("@comvi/vue", "@comvi/core");

    nuxt.options.vite = nuxt.options.vite || {};
    nuxt.options.vite.optimizeDeps = nuxt.options.vite.optimizeDeps || {};
    nuxt.options.vite.optimizeDeps.include = nuxt.options.vite.optimizeDeps.include || [];
    nuxt.options.vite.optimizeDeps.include.push("@comvi/vue", "@comvi/core");

    const localePrefix = options.localePrefix ?? "as-needed";
    const defaultLocale = options.defaultLocale;

    if (localePrefix !== "never") {
      extendPages((pages) => {
        const localizedPages: NuxtPage[] = [];

        const withLocalePrefix = (path: string, locale: string): string => {
          if (path === "/") {
            return `/${locale}`;
          }
          // Child route paths are often relative (e.g. "settings").
          // Only absolute route paths should get locale prefixes.
          if (path.startsWith("/")) {
            return `/${locale}${path}`;
          }
          return path;
        };

        const clonePageWithPrefix = (page: NuxtPage, locale: string): NuxtPage => {
          return {
            ...page,
            path: withLocalePrefix(page.path, locale),
            name: page.name ? `${page.name}___${locale}` : undefined,
            children: page.children?.map((child) => clonePageWithPrefix(child, locale)),
          };
        };

        const rootPages = pages.filter(
          (page) => !isLocaleParamRoute(page.path) && !page.file?.includes("[locale]"),
        );

        for (const locale of localeCodes) {
          const shouldPrefix =
            localePrefix === "always" || (localePrefix === "as-needed" && locale !== defaultLocale);

          if (shouldPrefix) {
            for (const page of rootPages) {
              localizedPages.push(clonePageWithPrefix(page, locale));
            }
          }
        }

        pages.push(...localizedPages);

        if (localePrefix === "always" && rootPages.length > 0) {
          // In `always` mode only prefixed routes may exist.
          for (let i = pages.length - 1; i >= 0; i--) {
            if (rootPages.includes(pages[i])) {
              pages.splice(i, 1);
            }
          }
        }

        const localeRouteIndex = pages.findIndex(
          (page) => isLocaleParamRoute(page.path) || page.file?.includes("[locale]"),
        );
        if (localeRouteIndex !== -1) {
          for (let i = pages.length - 1; i >= 0; i--) {
            if (isLocaleParamRoute(pages[i].path) || pages[i].file?.includes("[locale]")) {
              pages.splice(i, 1);
            }
          }
        }
      });
    }
  },
});

export default comviNuxtModule;
