/** Schema keys arrive as `"namespace:key"`, e.g. `"common:greeting"`. */

import type { ProjectSchema, SchemaParam } from "../types";

export interface TypeEmitterOptions {
  /**
   * Whether params are required (true) or optional (false)
   * @default true
   */
  strictParams?: boolean;

  /**
   * Default namespace name. Keys from this namespace will be generated
   * without the namespace prefix for cleaner autocomplete.
   * @default 'default'
   * @example
   * // With defaultNsName: 'default'
   * // 'default:home.title' → 'home.title'
   * // 'admin:dashboard' → 'admin:dashboard'
   */
  defaultNsName?: string;
}

export class TypeEmitter {
  generate(schema: ProjectSchema, options: TypeEmitterOptions = {}): string {
    const { strictParams = true, defaultNsName = "default" } = options;

    const lines: string[] = [
      "/**",
      " * Auto-generated translation keys",
      " * DO NOT EDIT MANUALLY - This file is generated by @comvi/cli",
      ` * Generated at: ${new Date().toISOString()}`,
      " */",
      "",
      "// Import to ensure module is resolved before augmentation",
      "import '@comvi/core';",
      "",
      "declare module '@comvi/core' {",
      "  interface TranslationKeys {",
    ];

    const flatKeys = this.convertToFlatKeys(schema.keys, defaultNsName);
    const sortedKeys = Object.keys(flatKeys).sort();

    for (const key of sortedKeys) {
      lines.push(this.generateKeyType(key, flatKeys[key].params, "    ", strictParams));
    }

    lines.push("  }");
    lines.push("}");
    lines.push("");

    // Export to make this a module file (required for module augmentation)
    lines.push("export {};");
    lines.push("");

    return lines.join("\n");
  }

  private generateKeyType(
    key: string,
    params: SchemaParam[],
    indent: string,
    strictParams: boolean,
  ): string {
    if (params.length === 0) {
      return `${indent}'${key}': never;`;
    }

    const paramTypes = params.map((param) => {
      const optional = strictParams ? "" : "?";
      return `${param.name}${optional}: ${param.type}`;
    });

    return `${indent}'${key}': { ${paramTypes.join("; ")} };`;
  }

  /**
   * Keys from the default namespace lose their prefix.
   *
   * @example
   * // With defaultNsName = 'default':
   * // 'default:home.title' → 'home.title'
   * // 'admin:dashboard' → 'admin:dashboard'
   */
  private convertToFlatKeys(
    keys: Record<string, { params: SchemaParam[] }>,
    defaultNsName: string,
  ): Record<string, { params: SchemaParam[] }> {
    const result: Record<string, { params: SchemaParam[] }> = {};
    const defaultPrefix = `${defaultNsName}:`;

    for (const [fullKey, keySchema] of Object.entries(keys)) {
      const emittedKey = fullKey.startsWith(defaultPrefix)
        ? fullKey.slice(defaultPrefix.length)
        : fullKey;

      if (result[emittedKey]) {
        throw new Error(
          `Translation key collision after stripping default namespace '${defaultNsName}': '${fullKey}' maps to '${emittedKey}'`,
        );
      }

      result[emittedKey] = keySchema;
    }

    return result;
  }
}
