import { describe, it, expect } from "vitest";
import { emitDeclarations } from "../src/emit";
import type { ProjectSchema } from "../src/extract";

/** The emitted `TranslationKeys` member lines, in emitted order, without indentation. */
function keyLinesOf(output: string): string[] {
  return (output.match(/^ {4}'.*$/gm) ?? []).map((line) => line.trim());
}

describe("emitDeclarations", () => {
  it("should generate valid .d.ts with keys", () => {
    const schema: ProjectSchema = {
      keys: {
        "common:greeting": { params: [{ name: "name", type: "string" }] },
        "common:logout": { params: [] },
        "admin:dashboard": { params: [] },
      },
    };

    const result = emitDeclarations(schema, { defaultNs: "common" });

    expect(result).toBe(
      [
        "/**",
        " * Auto-generated translation keys",
        " * DO NOT EDIT — regenerated by @comvi/vite-plugin on every file change",
        " */",
        "",
        "// Import to ensure module is resolved before augmentation",
        "import '@comvi/core';",
        "",
        "declare module '@comvi/core' {",
        "  interface TranslationKeys {",
        "    'admin:dashboard': never;",
        "    'greeting': { name: string };",
        "    'logout': never;",
        "  }",
        "}",
        "",
        "export {};",
        "",
      ].join("\n"),
    );
  });

  it("emits the empty skeleton for a schema with no keys", () => {
    const result = emitDeclarations({ keys: {} });

    expect(keyLinesOf(result)).toEqual([]);
    expect(result).toContain("  interface TranslationKeys {\n  }");
    expect(result).toContain("export {};");
  });

  it("should strip default namespace prefix", () => {
    const schema: ProjectSchema = {
      keys: {
        "default:title": { params: [] },
        "admin:title": { params: [] },
      },
    };

    const result = emitDeclarations(schema);

    expect(keyLinesOf(result)).toEqual(["'admin:title': never;", "'title': never;"]);
  });

  it("should handle plural params as number", () => {
    const schema: ProjectSchema = {
      keys: {
        "default:items": {
          params: [{ name: "count", type: "number" }],
        },
      },
    };

    const result = emitDeclarations(schema);

    expect(keyLinesOf(result)).toEqual(["'items': { count: number };"]);
  });

  it("should make params optional when strictParams is false", () => {
    const schema: ProjectSchema = {
      keys: {
        "default:greeting": {
          params: [{ name: "name", type: "string" }],
        },
      },
    };

    const result = emitDeclarations(schema, { strictParams: false });

    expect(keyLinesOf(result)).toEqual(["'greeting': { name?: string };"]);
  });

  it("should sort keys alphabetically", () => {
    const schema: ProjectSchema = {
      keys: {
        "default:zebra": { params: [] },
        "default:alpha": { params: [] },
        "default:middle": { params: [] },
      },
    };

    const result = emitDeclarations(schema);

    expect(keyLinesOf(result)).toEqual(["'alpha': never;", "'middle': never;", "'zebra': never;"]);
  });

  it("should emit stable output for unchanged schema", () => {
    const schema: ProjectSchema = {
      keys: {
        "default:greeting": {
          params: [{ name: "name", type: "string" }],
        },
      },
    };

    const first = emitDeclarations(schema);
    const second = emitDeclarations(schema);

    expect(first).toBe(second);
    expect(first).not.toContain("Generated at:");
  });
});
