/**
 * Emit TypeScript declaration file from a ProjectSchema.
 *
 * Reuses the same output format as @comvi/cli's TypeEmitter.
 */

import type { ProjectSchema, SchemaParam } from "./extract";

export interface EmitOptions {
  /** Make params required (true) or optional (false). @default true */
  strictParams?: boolean;
  /** Default namespace — keys from this ns drop their prefix. @default 'default' */
  defaultNs?: string;
}

/**
 * Generate .d.ts content from a project schema.
 */
export function emitDeclarations(schema: ProjectSchema, options: EmitOptions = {}): string {
  const { strictParams = true, defaultNs = "default" } = options;
  const defaultPrefix = `${defaultNs}:`;

  const lines: string[] = [
    "/**",
    " * Auto-generated translation keys",
    " * DO NOT EDIT — regenerated by @comvi/vite-plugin on every file change",
    " */",
    "",
    "// Import to ensure module is resolved before augmentation",
    "import '@comvi/core';",
    "",
    "declare module '@comvi/core' {",
    "  interface TranslationKeys {",
  ];

  // Sort keys, strip default namespace prefix
  const entries = Object.entries(schema.keys)
    .map(([fullKey, keySchema]) => {
      const displayKey = fullKey.startsWith(defaultPrefix)
        ? fullKey.slice(defaultPrefix.length)
        : fullKey;
      return [displayKey, keySchema.params] as const;
    })
    .sort(([a], [b]) => a.localeCompare(b));

  for (const [key, params] of entries) {
    lines.push(formatKeyType(key, params, "    ", strictParams));
  }

  lines.push("  }");
  lines.push("}");
  lines.push("");
  lines.push("export {};");
  lines.push("");

  return lines.join("\n");
}

function formatKeyType(
  key: string,
  params: SchemaParam[],
  indent: string,
  strictParams: boolean,
): string {
  if (params.length === 0) {
    return `${indent}'${key}': never;`;
  }

  const paramTypes = params.map((p) => {
    const optional = strictParams ? "" : "?";
    return `${p.name}${optional}: ${p.type}`;
  });

  return `${indent}'${key}': { ${paramTypes.join("; ")} };`;
}
