declare module "#build/comvi.setup" {
  // The plugin and the server utilities hand this whatever host the app was
  // built with, so the accepted context is host-typed. What the USER's hook
  // sees is `NuxtI18nSetup<C>` (core's base `I18n` by default) — the generated
  // template forwards the context untyped, so the two sides stay typed for
  // their own audiences.
  export function runComviSetup(
    context: import("../types").NuxtI18nSetupContext<import("@comvi/core").WrapperI18nHost>,
  ): Promise<void>;
}

declare module "#build/comvi.host" {
  // Generated by the module (src/module.ts): the BUILD-TIME branch between
  // nuxt's default `@comvi/vue` construction path and the app's `hostModule`.
  // Which branch is emitted decides WHICH of the two graphs the bundle gets —
  // not whether `@comvi/core` is in it, since a `hostModule` factory imports
  // the base root itself — so it cannot be a runtime conditional here
  // (framework-slim P4 step 5).
  export function createComviI18n<D extends import("@comvi/core").DefaultTranslationParams = {}>(
    options: import("@comvi/vue").VueI18nOptions<D>,
  ): import("@comvi/vue").AnyVueI18n;

  export function createComviCore<D extends import("@comvi/core").DefaultTranslationParams = {}>(
    options: import("@comvi/core").I18nOptions<D>,
  ): import("../types").NuxtServerHost;
}
